# Generated by Django 5.2.3 on 2025-06-28 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(verbose_name=50)),
                ('email', models.CharField(verbose_name=50)),
                ('phone', models.CharField(verbose_name=50)),
                ('content', models.TextField()),
            ],
        ),
    ]
